# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/eschulte/lisp/local-projects/gtirb

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/eschulte/lisp/local-projects/gtirb

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/eschulte/lisp/local-projects/gtirb/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eschulte/lisp/local-projects/gtirb/CMakeFiles /home/eschulte/lisp/local-projects/gtirb/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eschulte/lisp/local-projects/gtirb/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f googletest-build/googlemock/CMakeFiles/gmock.dir/build.make googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f googletest-build/googletest/CMakeFiles/gtest.dir/build.make googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtirb

# Build rule for target.
gtirb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtirb
.PHONY : gtirb

# fast build rule for target.
gtirb/fast:
	$(MAKE) -f src/CMakeFiles/gtirb.dir/build.make src/CMakeFiles/gtirb.dir/build
.PHONY : gtirb/fast

#=============================================================================
# Target rules for targets named proto

# Build rule for target.
proto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 proto
.PHONY : proto

# fast build rule for target.
proto/fast:
	$(MAKE) -f src/proto/CMakeFiles/proto.dir/build.make src/proto/CMakeFiles/proto.dir/build
.PHONY : proto/fast

#=============================================================================
# Target rules for targets named TestGTIRB

# Build rule for target.
TestGTIRB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestGTIRB
.PHONY : TestGTIRB

# fast build rule for target.
TestGTIRB/fast:
	$(MAKE) -f src/test/CMakeFiles/TestGTIRB.dir/build.make src/test/CMakeFiles/TestGTIRB.dir/build
.PHONY : TestGTIRB/fast

#=============================================================================
# Target rules for targets named gtirbTestInputBinary32

# Build rule for target.
gtirbTestInputBinary32: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtirbTestInputBinary32
.PHONY : gtirbTestInputBinary32

# fast build rule for target.
gtirbTestInputBinary32/fast:
	$(MAKE) -f src/test/testInputBinary/CMakeFiles/gtirbTestInputBinary32.dir/build.make src/test/testInputBinary/CMakeFiles/gtirbTestInputBinary32.dir/build
.PHONY : gtirbTestInputBinary32/fast

#=============================================================================
# Target rules for targets named gtirbTestInputBinary64

# Build rule for target.
gtirbTestInputBinary64: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtirbTestInputBinary64
.PHONY : gtirbTestInputBinary64

# fast build rule for target.
gtirbTestInputBinary64/fast:
	$(MAKE) -f src/test/testInputBinary/CMakeFiles/gtirbTestInputBinary64.dir/build.make src/test/testInputBinary/CMakeFiles/gtirbTestInputBinary64.dir/build
.PHONY : gtirbTestInputBinary64/fast

#=============================================================================
# Target rules for targets named gtirbTestInputBinary8

# Build rule for target.
gtirbTestInputBinary8: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtirbTestInputBinary8
.PHONY : gtirbTestInputBinary8

# fast build rule for target.
gtirbTestInputBinary8/fast:
	$(MAKE) -f src/test/testInputBinary/CMakeFiles/gtirbTestInputBinary8.dir/build.make src/test/testInputBinary/CMakeFiles/gtirbTestInputBinary8.dir/build
.PHONY : gtirbTestInputBinary8/fast

#=============================================================================
# Target rules for targets named gtirbTestInputBinary2

# Build rule for target.
gtirbTestInputBinary2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtirbTestInputBinary2
.PHONY : gtirbTestInputBinary2

# fast build rule for target.
gtirbTestInputBinary2/fast:
	$(MAKE) -f src/test/testInputBinary/CMakeFiles/gtirbTestInputBinary2.dir/build.make src/test/testInputBinary/CMakeFiles/gtirbTestInputBinary2.dir/build
.PHONY : gtirbTestInputBinary2/fast

#=============================================================================
# Target rules for targets named gtirbTestInputBinary16

# Build rule for target.
gtirbTestInputBinary16: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtirbTestInputBinary16
.PHONY : gtirbTestInputBinary16

# fast build rule for target.
gtirbTestInputBinary16/fast:
	$(MAKE) -f src/test/testInputBinary/CMakeFiles/gtirbTestInputBinary16.dir/build.make src/test/testInputBinary/CMakeFiles/gtirbTestInputBinary16.dir/build
.PHONY : gtirbTestInputBinary16/fast

#=============================================================================
# Target rules for targets named pygtirb

# Build rule for target.
pygtirb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pygtirb
.PHONY : pygtirb

# fast build rule for target.
pygtirb/fast:
	$(MAKE) -f python/CMakeFiles/pygtirb.dir/build.make python/CMakeFiles/pygtirb.dir/build
.PHONY : pygtirb/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f doc/CMakeFiles/doc.dir/build.make doc/CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named cpp_doxyout

# Build rule for target.
cpp_doxyout: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpp_doxyout
.PHONY : cpp_doxyout

# fast build rule for target.
cpp_doxyout/fast:
	$(MAKE) -f doc/cpp/CMakeFiles/cpp_doxyout.dir/build.make doc/cpp/CMakeFiles/cpp_doxyout.dir/build
.PHONY : cpp_doxyout/fast

#=============================================================================
# Target rules for targets named sphinx

# Build rule for target.
sphinx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sphinx
.PHONY : sphinx

# fast build rule for target.
sphinx/fast:
	$(MAKE) -f doc/python/CMakeFiles/sphinx.dir/build.make doc/python/CMakeFiles/sphinx.dir/build
.PHONY : sphinx/fast

#=============================================================================
# Target rules for targets named doc_examples

# Build rule for target.
doc_examples: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc_examples
.PHONY : doc_examples

# fast build rule for target.
doc_examples/fast:
	$(MAKE) -f doc/examples/CMakeFiles/doc_examples.dir/build.make doc/examples/CMakeFiles/doc_examples.dir/build
.PHONY : doc_examples/fast

#=============================================================================
# Target rules for targets named ex-jumps

# Build rule for target.
ex-jumps: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ex-jumps
.PHONY : ex-jumps

# fast build rule for target.
ex-jumps/fast:
	$(MAKE) -f doc/examples/CMakeFiles/ex-jumps.dir/build.make doc/examples/CMakeFiles/ex-jumps.dir/build
.PHONY : ex-jumps/fast

#=============================================================================
# Target rules for targets named ex-functions

# Build rule for target.
ex-functions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ex-functions
.PHONY : ex-functions

# fast build rule for target.
ex-functions/fast:
	$(MAKE) -f doc/examples/CMakeFiles/ex-functions.dir/build.make doc/examples/CMakeFiles/ex-functions.dir/build
.PHONY : ex-functions/fast

#=============================================================================
# Target rules for targets named ex-cfg-paths

# Build rule for target.
ex-cfg-paths: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ex-cfg-paths
.PHONY : ex-cfg-paths

# fast build rule for target.
ex-cfg-paths/fast:
	$(MAKE) -f doc/examples/CMakeFiles/ex-cfg-paths.dir/build.make doc/examples/CMakeFiles/ex-cfg-paths.dir/build
.PHONY : ex-cfg-paths/fast

#=============================================================================
# Target rules for targets named ex-data-symbols

# Build rule for target.
ex-data-symbols: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ex-data-symbols
.PHONY : ex-data-symbols

# fast build rule for target.
ex-data-symbols/fast:
	$(MAKE) -f doc/examples/CMakeFiles/ex-data-symbols.dir/build.make doc/examples/CMakeFiles/ex-data-symbols.dir/build
.PHONY : ex-data-symbols/fast

#=============================================================================
# Target rules for targets named general_doxyout

# Build rule for target.
general_doxyout: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 general_doxyout
.PHONY : general_doxyout

# fast build rule for target.
general_doxyout/fast:
	$(MAKE) -f doc/general/CMakeFiles/general_doxyout.dir/build.make doc/general/CMakeFiles/general_doxyout.dir/build
.PHONY : general_doxyout/fast

#=============================================================================
# Target rules for targets named gtirb_api-1.2.0

# Build rule for target.
gtirb_api-1.2.0: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtirb_api-1.2.0
.PHONY : gtirb_api-1.2.0

# fast build rule for target.
gtirb_api-1.2.0/fast:
	$(MAKE) -f java/CMakeFiles/gtirb_api-1.2.0.dir/build.make java/CMakeFiles/gtirb_api-1.2.0.dir/build
.PHONY : gtirb_api-1.2.0/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... package_source"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... package"
	@echo "... test"
	@echo "... gmock_main"
	@echo "... gmock"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... gtirb"
	@echo "... proto"
	@echo "... TestGTIRB"
	@echo "... gtirbTestInputBinary32"
	@echo "... gtirbTestInputBinary64"
	@echo "... gtirbTestInputBinary8"
	@echo "... gtirbTestInputBinary2"
	@echo "... gtirbTestInputBinary16"
	@echo "... pygtirb"
	@echo "... doc"
	@echo "... cpp_doxyout"
	@echo "... sphinx"
	@echo "... doc_examples"
	@echo "... ex-jumps"
	@echo "... ex-functions"
	@echo "... ex-cfg-paths"
	@echo "... ex-data-symbols"
	@echo "... general_doxyout"
	@echo "... gtirb_api-1.2.0"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

